#!/usr/bin/env bash
# Display all info about subdomains.
display () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomains " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    display "$1" "www"
    display "$1" "lb-01"
    display "$1" "web-01"
    display "$1" "web-02"
elif [ "$#" == 2 ]
then
    display "$1" "$2"
fi
