#!/usr/bin/env bash
#To infinity and beyond indefinitely
#with a sleep 2 in between each interation
#I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while (true)
	do
		echo "To infinity and beyond"
		sleep 2
done
