#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -lt 10 ]
	do 
		echo "Holberton School"
	if [[ $i == 3 ]];
	then
		echo "bad luck"
	fi
	if [[ $i == 7 ]];
	then
		echo "good luck"
	fi
	((i=i+1))
done
