#!/usr/bin/env bash
# Run Nginx as Nginx and update port 80 to 8080 change permission
pkill apache2 
pkill nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 600 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
